Initial commit of mobile screen templates
K2InformaticsGmbH/k2informaticsgmbh.github.io pull request #1
Opened 2018-08-27 19:38 UTC by janmenjoyroy

Screen templates for mobile browser support. 
Screens provided for the following:
1. Home Page or the very first launching page
2. Services page
3. Services ---> Consultation page
4. Services menu page
5. 3. Services ---> Consultation menu page
6. Companies ---> Location map page
7. Companies ---> Team/partner page
8. Companies ---> Team/partner Details page

2018-09-04 21:12 UTC, c-bik requested changes
Use npm for bootstrap and font awesome libraries (js+css). Not a copy of 3rd party packages in our repo!

Refer to sample in development branch as how it should be done:
https://github.com/K2InformaticsGmbH/k2informaticsgmbh.github.io/blob/d9dfc01157863711ff20b807a26bcb397dd2c490/dev/package.json#L40-L46
https://github.com/K2InformaticsGmbH/k2informaticsgmbh.github.io/blob/d9dfc01157863711ff20b807a26bcb397dd2c490/dev/index.js#L1-L4

Ideally other than HTML, custom scss etc only package.json changes are desired!

2018-09-10 04:40 UTC, c-bik approved these changes

2018-09-10 04:41 UTC, c-bik requested changes
the **public** produced by `npm run build` is missing files:
![image](https://user-images.githubusercontent.com/913008/45276758-7091e780-b4c4-11e8-9fd2-b4c94a10bc0c.png)

I could view the work-in-progress with `npm start`! It looks like a good start with responsive in a few decives (checked with chrome **Device Toolbar**).

**To collect feedback from others, we need to be able to generate the public folder to host at https://k2informaticsgmbh.github.io/ !** - _please see fix this_

2018-09-17 07:21 UTC, c-bik approved these changes

2018-09-17 07:52 UTC, shamis reviewed
- Title and fav icon is not set i think
- Footer on larger screens are not on the foot of the page
- Services and Solutions link on the page does not go the header services and solutions links

2018-10-01 11:36 UTC, c-bik requested changes
@janmenjoyroy Unfortunately I could not compile to check your last commit.

### Fix package vulnarebilities
```sh
$ npm install
...
added 1618 packages from 903 contributors and audited 17698 packages in 186.356s
found 46 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

### Fix compile errors
```sh
$ npm run build

> k2informaticsgmbh.github.io@1.0.0 build ...\k2informaticsgmbh.github.io\dev
> webpack --progress --colors --config webpack.prod.js

...\k2informaticsgmbh.github.io\dev\node_modules\webpack-cli\bin\config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (...\k2informaticsgmbh.github.io\dev\node_modules\webpack-cli\bin\config-yargs.js:89:48)
    at ...\k2informaticsgmbh.github.io\dev\node_modules\webpack-cli\bin\webpack.js:60:27
    at Object.<anonymous> (...\k2informaticsgmbh.github.io\dev\node_modules\webpack-cli\bin\webpack.js:515:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! k2informaticsgmbh.github.io@1.0.0 build: `webpack --progress --colors --config webpack.prod.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the k2informaticsgmbh.github.io@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ...\AppData\Roaming\npm-cache\_logs\2018-10-01T11_30_35_183Z-debug.log
```

I will continue my review after these are fixed!

2018-10-09 17:04 UTC, shamis commented
@janmenjoyroy, I am also getting the same error as @c-bik .
node version is 8.11.1
npm version is 6.3.0
Please let me know if there some other parameter has to be checked.

2018-10-12 09:00 UTC, c-bik commented
@shamis it compiles now and `npm start` alos works for quickly checking the progress. Can you please verify if your review comments are addressed as you expected?

2018-10-12 13:28 UTC, c-bik commented
@janmenjoyroy can you please have a look at review comments from @shamis above. Please also lowercase all files extensions for consistancy

I don't see the following translations files

![image](https://user-images.githubusercontent.com/913008/46871824-afec8480-ce32-11e8-8a56-2d019f42f412.png)

being copied to `public`

![image](https://user-images.githubusercontent.com/913008/46871866-cc88bc80-ce32-11e8-87d6-04f797e1658f.png)

**we need them in `public` in order to change the language specific page translations live (WITHOUT `npm run build`)**

Instead of
```sh
locales
|-- de
|   `-- translation.json
`-- en
    `-- translation.json
```
can it be
```sh
translations
|-- de.json
|-- it.json
|-- fr.json
`-- en.json
```

2018-10-12 13:32 UTC, c-bik commented
![image](https://user-images.githubusercontent.com/913008/46872295-fe4e5300-ce33-11e8-975d-1798ff11a5b8.png)
Change to **K2 Informatics GmbH**

2018-10-12 13:34 UTC, c-bik requested changes
![image](https://user-images.githubusercontent.com/913008/46872295-fe4e5300-ce33-11e8-975d-1798ff11a5b8.png)
Change to **K2 Informatics GmbH**

can you please have a look at review comments from @shamis above. Please also lowercase all files extensions for consistancy

I don't see the following translations files

![image](https://user-images.githubusercontent.com/913008/46871824-afec8480-ce32-11e8-8a56-2d019f42f412.png)

being copied to `public`

![image](https://user-images.githubusercontent.com/913008/46871866-cc88bc80-ce32-11e8-87d6-04f797e1658f.png)

**we need them in `public` in order to change the language specific page translations live (WITHOUT `npm run build`)**

Instead of
```sh
locales
|-- de
|   `-- translation.json
`-- en
    `-- translation.json
```
can it be
```sh
translations
|-- de.json
|-- it.json
|-- fr.json
`-- en.json
```

2018-10-14 07:38 UTC, c-bik approved these changes

2018-10-14 07:44 UTC, c-bik requested changes
Ref: https://github.com/K2InformaticsGmbH/k2informaticsgmbh.github.io/pull/1#pullrequestreview-164243204
1. Company name correction at footer at footer isn't fixed!
1. Changing translation in public/translations/_language_.json doesn't load on page reload
1. URL should change based on laguage selection (default _for now_ `en`). E.g. `http://localhost:8082/en` etc

2018-10-14 17:03 UTC, janmenjoyroy commented
@c-bik I am yet to fix:
1. Changing translation in public/translations/language.json doesn't load on page reload
2. URL should change based on laguage selection (default for now en). E.g. http://localhost:8082/en etc

2018-10-15 17:20 UTC, janmenjoyroy commented
Fixed all comments; @c-bik @shamis please review and let me know in case of any issue.

2018-10-17 06:18 UTC, c-bik commented
> Fixed all comments; @c-bik @shamis please review and let me know in case of any issue.

Please also address the following:
![image](https://user-images.githubusercontent.com/913008/47065954-f819f700-d1e4-11e8-8926-7dbbe3bca596.png)

![image](https://user-images.githubusercontent.com/913008/47066012-24ce0e80-d1e5-11e8-816d-7448a84bca1f.png)

2018-10-17 06:30 UTC, c-bik requested changes
1. Delete `dev/assets/magnific-popup` (if needed use `npm` to import it)
1. Move `dev/assets/js` to `dev/js`
1. Delete any unused assets (except the CI folder)

2018-10-17 06:30 UTC, c-bik commented on dev/assets/magnific-popup/magnific-popup.js
> +/*! Magnific Popup - v1.1.0 - 2016-02-20
Is it used?
Can it be imported through `npm` instead, if required?

2018-10-17 06:30 UTC, c-bik commented on dev/package-lock.json
> +      "version": "0.2.6",
Delete this from repo, and list in .gitignore!
No need to version lock files when developing

2018-10-17 06:30 UTC, c-bik commented on dev/assets/js/main.js
> +$(document).ready(function ($) {
Use shorthad construct
```js
$(function ...
```
See `index.js`

2018-10-26 06:51 UTC, c-bik commented
@janmenjoyroy 
```bash
Bikram@WKS006 MINGW64 /c/projects/git/K2InformaticsGmbH/k2informaticsgmbh.github.io/dev (janmenjoyroy-development)
$ npm run build

> k2informaticsgmbh.github.io@1.0.0 build C:\projects\git\K2InformaticsGmbH\k2informaticsgmbh.github.io\dev
> webpack --progress --colors --config webpack.prod.js

'webpack' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! k2informaticsgmbh.github.io@1.0.0 build: `webpack --progress --colors --config webpack.prod.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the k2informaticsgmbh.github.io@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bikram\AppData\Roaming\npm-cache\_logs\2018-10-26T06_49_47_968Z-debug.log
```

@shamis can you please verify/confirm? _my other npm projects are compiling fine_

2018-10-26 06:54 UTC, c-bik commented
@janmenjoyroy

**looks like you keep missing this one! (been reported by me and @shamis above)**

![image](https://user-images.githubusercontent.com/913008/47549492-87698d80-d8fc-11e8-9f4f-662982c926df.png)

Please fix!

2018-10-26 06:59 UTC, acautin commented
@c-bik for me it is building fine after clean clone on OS X, are you sure your ``npm install`` completed successfully ?

2018-10-26 07:00 UTC, c-bik commented
> @c-bik for me it is building fine after clean clone on OS X, are you sure your `npm install` completed successfully ?

Didn't try a clean clone! Will try shortly and report back soon (thanks for headsup 👍 )!

2018-10-26 07:34 UTC, c-bik commented
@janmenjoyroy 
![image](https://user-images.githubusercontent.com/913008/47551320-280e7c00-d902-11e8-810a-2d6d84fce001.png)

This needs to work!

2018-10-27 17:01 UTC, janmenjoyroy commented
> @janmenjoyroy
> ![image](https://user-images.githubusercontent.com/913008/47551320-280e7c00-d902-11e8-810a-2d6d84fce001.png)
> 
> This needs to work!

@c-bik and @shamis, I need your help in resolving this. Please guide me on how to fix this type of issue.

2018-11-08 09:31 UTC, acautin commented
@janmenjoyroy @c-bik I haven't tested it but think the problem is the ajax request are not supported when using the file:// protocol, to test it you need add it to a server for it to work via the http:// protocol.

2018-11-08 09:36 UTC, c-bik commented
> @janmenjoyroy @c-bik I haven't tested it but think the problem is the ajax request are not supported when using the file:// protocol, to test it you need add it to a server for it to work via the http:// protocol.

@acautin 👍 So my test was flawed. I think this issue doesn't exist with `npm start` (_I will verify again and confirm_).

I, however, am quite sure that even with `npm start` (i.e. running a webpack server) the live translation change still doesn't work! (@janmenjoyroy can you please confirm?)

2018-11-08 10:35 UTC, janmenjoyroy commented
Hi Agustin,
Nice to meet you !!
Just to keep you updated, we are working on the UI development of the new website for K2i.
We have built the web pages to support multiple languages. We use AJAX to load the language JSON files.This features is working fine using a local server. But we face the said issue when we load this webpage statically (in a browser); basically we open it without any server.
We get the following error "failed to load file://...../locals/en/translation.json", when we try to open the page statically.
Most of the blogs suggested either to use a local web server or upload the language file to another server.(viz. "Cross origin requests are only supported for HTTP." error when loading a local file)

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
"Cross origin requests are only supported for HTTP." error when loading ...

I'm trying to load a 3D model into Three.js with JSONLoader, and that 3D model is in the same directory as the e...
 |

 |

 |




I am stuck with this issue for sometime and it will be really helpful if you please suggest me some way out for this issue.
Regards, Janmenjoy Roy 
 

    On Thursday, 8 November, 2018, 3:06:59 PM IST, Bikram Chatterjee <notifications@github.com> wrote:  
 
 

@janmenjoyroy @c-bik I haven't tested it but think the problem is the ajax request are not supported when using the file:// protocol, to test it you need add it to a server for it to work via the http:// protocol.


@acautin 👍 So my test was flawed. I think this issue doesn't exist with npm start (I will verify again and confirm).

I, however, am quite sure that even with npm start (i.e. running a webpack server) the live translation change still doesn't work! (@janmenjoyroy can you please confirm?)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

2018-11-08 12:18 UTC, acautin commented
Well I think it will never work locally as the file:// protocol is not supported, you should test if the translations work when using a local test server, for example with ``npm start``. If that works then it should be fine.

2018-11-08 19:07 UTC, janmenjoyroy commented
> > @janmenjoyroy @c-bik I haven't tested it but think the problem is the ajax request are not supported when using the file:// protocol, to test it you need add it to a server for it to work via the http:// protocol.
> 
> @acautin 👍 So my test was flawed. I think this issue doesn't exist with `npm start` (_I will verify again and confirm_).
> 
> I, however, am quite sure that even with `npm start` (i.e. running a webpack server) the live translation change still doesn't work! (@janmenjoyroy can you please confirm?)

@c-bik, regarding your last query, I have carried out the following steps and found that live translation changes get reflected on browser reload. I have carried out the test with a fresh cloned code base.
1. run *npm install* and then *npm start* (the home page gets opened automatically)
2. change the language JSON file
3.  reload the browser
4. verify the changes in the web page

Is my understanding correct? Or did I miss out any step?

2018-11-08 22:11 UTC, c-bik commented
> > > @janmenjoyroy @c-bik I haven't tested it but think the problem is the ajax request are not supported when using the file:// protocol, to test it you need add it to a server for it to work via the http:// protocol.
> > 
> > 
> > @acautin 👍 So my test was flawed. I think this issue doesn't exist with `npm start` (_I will verify again and confirm_).
> > I, however, am quite sure that even with `npm start` (i.e. running a webpack server) the live translation change still doesn't work! (@janmenjoyroy can you please confirm?)
> 
> @c-bik, regarding your last query, I have carried out the following steps and found that live translation changes get reflected on browser reload. I have carried out the test with a fresh cloned code base.
> 
> 1. run _npm install_ and then _npm start_ (the home page gets opened automatically)
> 2. change the language JSON file
> 3. reload the browser
> 4. verify the changes in the web page
> 
> Is my understanding correct? Or did I miss out any step?

@janmenjoyroy Thanks 👍 I will confirm tomorrow!

2018-11-09 13:36 UTC, c-bik commented
> > I, however, am quite sure that even with `npm start` (i.e. running a webpack server) the live translation change still doesn't work! (@janmenjoyroy can you please confirm?)
> 
> @c-bik, regarding your last query, I have carried out the following steps and found that live translation changes get reflected on browser reload. I have carried out the test with a fresh cloned code base.
> 
> 1. run _npm install_ and then _npm start_ (the home page gets opened automatically)
> 2. change the language JSON file
> 3. reload the browser
> 4. verify the changes in the web page
> 
> Is my understanding correct? Or did I miss out any step?

@janmenjoyroy Your understanding is correct, however when I follow the excat same steps as you understood I see the problem Step 4 (in your steps above) fails!

Here is what is happening to me...
![image](https://user-images.githubusercontent.com/913008/48265290-6f315c80-e42c-11e8-92dc-b14a52c38862.png)

@shamis / @acautin can you please confirm?

PS: @janmenjoyroy I fixed the other two issues you were stuck with (extension lower cased and `npm audit fix`) and committed my changes to your fork so that the PR is updated and merge conflict is now gone. Please pull into your setup.

2018-11-09 14:03 UTC, c-bik requested changes
### COSMETICS and CODE Cleanup
1. Remove all unused files:
For example *.psd files are shown modified in PR
![image](https://user-images.githubusercontent.com/913008/48265719-858be800-e42d-11e8-8f26-f3cffbed02d2.png) **is however _NOT_ referenced anywhere in code**
![image](https://user-images.githubusercontent.com/913008/48265799-c5eb6600-e42d-11e8-8b47-a08b630ffa0f.png) _few other unused files are with extenions eps, pdf, ai, svg etc_

2. Remove this change from PR
![image](https://user-images.githubusercontent.com/913008/48266202-fb448380-e42e-11e8-9d65-e08ca7122d33.png)

### IMPORTANT
Additionaly, @agustin and @shamis can you please do a coding, architecture, best practices review for @janmenjoyroy with improvement possibilities

2018-11-27 19:26 UTC, c-bik approved these changes

2018-11-27 19:43 UTC, c-bik requested changes
Code can be quite improved / rediced using some templating (like handlebars) and keeping styling out of JS code

2018-11-27 19:43 UTC, c-bik commented on dev/webpack.common.js
> +        // new favicon('./assets/images/logo.png')
remove commented lines

2018-11-27 19:43 UTC, c-bik commented on dev/webpack.common.js
> +                // use: ['style-loader', 'css-loader', 'postcss-loader', 'sass-loader']
remove commented lines

2018-11-27 19:43 UTC, c-bik commented on dev/webpack.dev.js
> +         contentBase: '../public'
revert indent (extra space)

2018-11-27 19:43 UTC, c-bik commented on dev/index.js
> +  headerElem = `${headerElem} <meta content="" name="description">`;
Do not inject HTML string. Construct shadow dom with jquery instead

2018-11-27 19:43 UTC, c-bik commented on dev/index.js
> +            "'></span>"
Do not inject HTML string, use jQuery to construct the dom to append.

2018-11-27 19:43 UTC, c-bik commented on dev/index.js
> +      });
reduce number of lines if it fits within 80 characters!

2018-12-06 06:41 UTC, janmenjoyroy commented
hi @acautin and @c-bik will you please review the code and provide me with your valuable feedback?
I have pushed all the changes requested by @c-bik.

2018-12-06 07:57 UTC, c-bik requested changes

2018-12-06 07:57 UTC, c-bik commented on dev/index.js
> +      "/": function () {
can you redirect this to `/:lang?/home` instead?

2018-12-06 07:57 UTC, c-bik commented on dev/index.js
> +        "<p data-i18n='[html]about_us.vision.contents." + i + "'></p>"
rewrite with `$('<p>').attr()` etc

2018-12-06 07:57 UTC, c-bik commented on dev/index.js
> +      '.name"></h5>'
rewrite `$('<h5>').attr(...)`

2018-12-06 07:57 UTC, c-bik commented on dev/index.js
> +      '<h5 style="font-size:16px" data-i18n="[html]about_us.teams.list.' +
use bootstrap class instead of style inlining wherever possible

2018-12-06 07:57 UTC, c-bik commented on dev/index.js
> +      .css({height: "40px"})
how does a hardcoded height becomes responsive?

2018-12-06 07:57 UTC, c-bik commented on dev/index.js
> +      '<span data-i18n="[html]about_us.support.contents.' + i + '"></span><br/>'
rewrite with jq

2018-12-06 07:57 UTC, c-bik commented on dev/index.js
> +          "<i class='fas fa-angle-double-right'></i>&nbsp;<span data-i18n='[html]about_us.jobs.contents." +
**rewrite all hard coded HTML fragment strings with jQuery EVERYWHERE** (was already the earlier review comment)

2018-12-10 06:35 UTC, acautin commented on dev/index.js
> +        router.navigate('/en/home');
is this always going to english ? should it not be `router.navigate(window.lang + '/home')` ?

2018-12-13 06:44 UTC, acautin commented
@janmenjoyroy sure I will, I need to discuss the goals of the project with @stoch  as I was not involved at the beginning.

2018-12-14 09:19 UTC, acautin commented
@janmenjoyroy I have reviewed a little bit the code, for me it seems there is in good state good job from you and @c-bik checking. But there are still a couple of details that need fixing:

The alignment on windows between 780 and 890 pixels wide is not proper:

![screen shot 2018-12-14 at 10 04 23](https://user-images.githubusercontent.com/949102/49994339-86aeb880-ff89-11e8-9d35-e48ace15062c.png)

The sandwich menu for mobile screens is also not working (translate or sections):

![screen shot 2018-12-14 at 10 05 33](https://user-images.githubusercontent.com/949102/49994408-bc53a180-ff89-11e8-93f5-62eb37d7aacd.png)

2018-12-17 06:52 UTC, c-bik commented
@acautin FYI:
https://github.com/K2InformaticsGmbH/k2informaticsgmbh.github.io/tree/master hosts for https://k2informaticsgmbh.github.io/

https://github.com/K2InformaticsGmbH/k2informaticsgmbh.github.io/tree/master/erloci_dev_setup is temporary home for from erloci docs @KarlKeiser generated (we will move it away from here into wiki eventually)!

2018-12-17 18:11 UTC, janmenjoyroy commented
@acautin I have fixed your following review comments:
1. The alignment on windows between 780 and 890 pixels wide is not proper
2. The sandwich menu for mobile screens is also not working (translate or sections)
Please review the same and let me know in case of any issue.

2018-12-18 07:33 UTC, acautin commented
@janmenjoyroy please do not comment out code, if is not usable anymore just remove it. It can still be retrieved by the git history and it is easier to see the difference.
There is duplicated code on the functions you added please extract into a separated function and call it instead.

2019-01-01 16:42 UTC, janmenjoyroy commented
@acautin @c-bik ... Happy New Year ...
Are there any other change requests from your end for the k2i website?

2019-02-07 07:19 UTC, c-bik approved these changes

2019-02-07 07:25 UTC, acautin commented
@janmenjoyroy thanks for your effort and the patience will merge now, to have this as our initial version of the page, we have some improvements that are going to come but in general if you want to think about how it could be implemented, changes are regarding making the team sections easier to modify and a better highlight of our current project.

2019-02-07 07:25 UTC, merged

2019-02-07 07:33 UTC, janmenjoyroy commented
@acautin @c-bik thank you for all your support.

@acautin can I have your Skype ID please? We can discuss regarding the improvisation of the team page at your convenience. And you can reach me at Skype: janmenjoyroy.

2019-02-07 07:48 UTC, acautin commented
@janmenjoyroy We don't have the plan yet, will discuss internally what are the goal and suggest a couple of alternatives during next week and will come back to you for a meeting, my initial idea would be some sort of json file from which the data can be loaded but is not yet finalized.

2019-02-07 09:22 UTC, acautin commented
@janmenjoyroy one unrelated small thing. Can you please check your ``git config --list`` and verify ``core.ignorecase=true`` if you use a windows or case insensitive Os X. Otherwise ``core.ignorecase=false`` for linux based systems. As to avoid including multiple versions of the same file with differences only in the casing. Thanks!